const express = require('express');
const path = require('path');
const fs = require('fs');
const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static('.'));

// Store contacts in memory (in production use database)
let contacts = [];
const CONTACTS_FILE = 'contacts.json';

// Load existing contacts
if (fs.existsSync(CONTACTS_FILE)) {
    try {
        const data = fs.readFileSync(CONTACTS_FILE, 'utf8');
        contacts = JSON.parse(data);
    } catch (error) {
        console.log('No existing contacts found, starting fresh');
    }
}

// Save contacts to file
function saveContacts() {
    fs.writeFileSync(CONTACTS_FILE, JSON.stringify(contacts, null, 2));
}

// Routes
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

// Get contact count
app.get('/api/count', (req, res) => {
    res.json({ count: contacts.length });
});

// Add contact
app.post('/api/contacts', (req, res) => {
    const { name, phone } = req.body;
    
    if (!name || !phone) {
        return res.status(400).json({ error: 'Name and phone are required' });
    }
    
    const newContact = {
        id: Date.now(),
        name,
        phone,
        timestamp: new Date().toISOString(),
        ip: req.ip
    };
    
    contacts.push(newContact);
    saveContacts();
    
    res.json({ 
        success: true, 
        count: contacts.length,
        contact: newContact
    });
});

// Download VCF
app.get('/api/download-vcf', (req, res) => {
    let vcfContent = '';
    
    contacts.forEach(contact => {
        vcfContent += `BEGIN:VCARD
VERSION:3.0
FN:🐢SILA🇹🇿 ${contact.name}
TEL:${contact.phone}
NOTE:Generated by SILA TECH VCF Collector
END:VCARD
`;
    });
    
    res.setHeader('Content-Type', 'text/vcard');
    res.setHeader('Content-Disposition', 'attachment; filename="New year VCF by SILA TECH.vcf"');
    res.send(vcfContent);
});

// Health check
app.get('/health', (req, res) => {
    res.json({ 
        status: 'OK', 
        contacts: contacts.length,
        timestamp: new Date().toISOString()
    });
});

// 404 handler
app.use((req, res) => {
    res.status(404).sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
    console.log(`📞 Total contacts: ${contacts.length}`);
    console.log(`🌐 Open: http://localhost:${PORT}`);
});
